import React from "react";
import { Box } from "@mui/material";
import ManagementGrade from "../../components/Table/ManagementGrade";
import MenuComponent from "../../components/LeftMenu/Menu";

const TeacherGrade = () => {
  // Dữ liệu ảo
  const fakeData = [
    // Class A, PT1
    {
      studentName: "John Doe",
      studentId: "S10001",
      quizName: "PT1",
      state: "done",
      submissionTime: "2023-07-01 10:00",
      score: 85,
      classId: "C1",
      className: "Class A",
    },
    {
      studentName: "Jane Smith",
      studentId: "S10002",
      quizName: "PT1",
      state: "done",
      submissionTime: "2023-07-01 10:05",
      score: 90,
      classId: "C1",
      className: "Class A",
    },
    {
      studentName: "Michael Johnson",
      studentId: "S10003",
      quizName: "PT1",
      state: "done",
      submissionTime: "2023-07-01 10:10",
      score: 88,
      classId: "C1",
      className: "Class A",
    },
    {
      studentName: "Emily Davis",
      studentId: "S10004",
      quizName: "PT1",
      state: "done",
      submissionTime: "2023-07-01 10:15",
      score: 92,
      classId: "C1",
      className: "Class A",
    },
    {
      studentName: "David Wilson",
      studentId: "S10005",
      quizName: "PT1",
      state: "done",
      submissionTime: "2023-07-01 10:20",
      score: 87,
      classId: "C1",
      className: "Class A",
    },
    {
      studentName: "Sarah Moore",
      studentId: "S10006",
      quizName: "PT1",
      state: "done",
      submissionTime: "2023-07-01 10:25",
      score: 89,
      classId: "C1",
      className: "Class A",
    },
    {
      studentName: "James Brown",
      studentId: "S10007",
      quizName: "PT1",
      state: "done",
      submissionTime: "2023-07-01 10:30",
      score: 91,
      classId: "C1",
      className: "Class A",
    },
    {
      studentName: "Jessica Taylor",
      studentId: "S10008",
      quizName: "PT1",
      state: "done",
      submissionTime: "2023-07-01 10:35",
      score: 94,
      classId: "C1",
      className: "Class A",
    },
    {
      studentName: "Robert Anderson",
      studentId: "S10009",
      quizName: "PT1",
      state: "done",
      submissionTime: "2023-07-01 10:40",
      score: 86,
      classId: "C1",
      className: "Class A",
    },
    {
      studentName: "Patricia Thomas",
      studentId: "S10010",
      quizName: "PT1",
      state: "done",
      submissionTime: "2023-07-01 10:45",
      score: 93,
      classId: "C1",
      className: "Class A",
    },
    // Class A, PT2
    {
      studentName: "John Doe",
      studentId: "S10001",
      quizName: "PT2",
      state: "done",
      submissionTime: "2023-07-02 10:00",
      score: 88,
      classId: "C1",
      className: "Class A",
    },
    {
      studentName: "Jane Smith",
      studentId: "S10002",
      quizName: "PT2",
      state: "done",
      submissionTime: "2023-07-02 10:05",
      score: 92,
      classId: "C1",
      className: "Class A",
    },
    {
      studentName: "Michael Johnson",
      studentId: "S10003",
      quizName: "PT2",
      state: "done",
      submissionTime: "2023-07-02 10:10",
      score: 85,
      classId: "C1",
      className: "Class A",
    },
    {
      studentName: "Emily Davis",
      studentId: "S10004",
      quizName: "PT2",
      state: "done",
      submissionTime: "2023-07-02 10:15",
      score: 90,
      classId: "C1",
      className: "Class A",
    },
    {
      studentName: "David Wilson",
      studentId: "S10005",
      quizName: "PT2",
      state: "done",
      submissionTime: "2023-07-02 10:20",
      score: 87,
      classId: "C1",
      className: "Class A",
    },
    {
      studentName: "Sarah Moore",
      studentId: "S10006",
      quizName: "PT2",
      state: "done",
      submissionTime: "2023-07-02 10:25",
      score: 91,
      classId: "C1",
      className: "Class A",
    },
    {
      studentName: "James Brown",
      studentId: "S10007",
      quizName: "PT2",
      state: "done",
      submissionTime: "2023-07-02 10:30",
      score: 89,
      classId: "C1",
      className: "Class A",
    },
    {
      studentName: "Jessica Taylor",
      studentId: "S10008",
      quizName: "PT2",
      state: "done",
      submissionTime: "2023-07-02 10:35",
      score: 94,
      classId: "C1",
      className: "Class A",
    },
    {
      studentName: "Robert Anderson",
      studentId: "S10009",
      quizName: "PT2",
      state: "done",
      submissionTime: "2023-07-02 10:40",
      score: 88,
      classId: "C1",
      className: "Class A",
    },
    {
      studentName: "Patricia Thomas",
      studentId: "S10010",
      quizName: "PT2",
      state: "done",
      submissionTime: "2023-07-02 10:45",
      score: 90,
      classId: "C1",
      className: "Class A",
    },
    // Class B, PT1
    {
      studentName: "Alice Martinez",
      studentId: "S20001",
      quizName: "PT1",
      state: "done",
      submissionTime: "2023-07-01 11:00",
      score: 84,
      classId: "C2",
      className: "Class B",
    },
    {
      studentName: "Tommy Lee",
      studentId: "S20002",
      quizName: "PT1",
      state: "done",
      submissionTime: "2023-07-01 11:05",
      score: 87,
      classId: "C2",
      className: "Class B",
    },
    {
      studentName: "Henry White",
      studentId: "S20003",
      quizName: "PT1",
      state: "done",
      submissionTime: "2023-07-01 11:10",
      score: 89,
      classId: "C2",
      className: "Class B",
    },
    {
      studentName: "Nancy Harris",
      studentId: "S20004",
      quizName: "PT1",
      state: "done",
      submissionTime: "2023-07-01 11:15",
      score: 85,
      classId: "C2",
      className: "Class B",
    },
    {
      studentName: "Chris Martin",
      studentId: "S20005",
      quizName: "PT1",
      state: "done",
      submissionTime: "2023-07-01 11:20",
      score: 90,
      classId: "C2",
      className: "Class B",
    },
    {
      studentName: "Amy Clark",
      studentId: "S20006",
      quizName: "PT1",
      state: "done",
      submissionTime: "2023-07-01 11:25",
      score: 92,
      classId: "C2",
      className: "Class B",
    },
    {
      studentName: "Brian Lewis",
      studentId: "S20007",
      quizName: "PT1",
      state: "done",
      submissionTime: "2023-07-01 11:30",
      score: 88,
      classId: "C2",
      className: "Class B",
    },
    {
      studentName: "Diana Walker",
      studentId: "S20008",
      quizName: "PT1",
      state: "done",
      submissionTime: "2023-07-01 11:35",
      score: 91,
      classId: "C2",
      className: "Class B",
    },
    {
      studentName: "Jack Hall",
      studentId: "S20009",
      quizName: "PT1",
      state: "done",
      submissionTime: "2023-07-01 11:40",
      score: 86,
      classId: "C2",
      className: "Class B",
    },
    {
      studentName: "Lily Allen",
      studentId: "S20010",
      quizName: "PT1",
      state: "done",
      submissionTime: "2023-07-01 11:45",
      score: 93,
      classId: "C2",
      className: "Class B",
    },
    // Class B, PT2
    {
      studentName: "Alice Martinez",
      studentId: "S20001",
      quizName: "PT2",
      state: "done",
      submissionTime: "2023-07-02 11:00",
      score: 89,
      classId: "C2",
      className: "Class B",
    },
    {
      studentName: "Tommy Lee",
      studentId: "S20002",
      quizName: "PT2",
      state: "done",
      submissionTime: "2023-07-02 11:05",
      score: 92,
      classId: "C2",
      className: "Class B",
    },
    {
      studentName: "Henry White",
      studentId: "S20003",
      quizName: "PT2",
      state: "done",
      submissionTime: "2023-07-02 11:10",
      score: 87,
      classId: "C2",
      className: "Class B",
    },
    {
      studentName: "Nancy Harris",
      studentId: "S20004",
      quizName: "PT2",
      state: "done",
      submissionTime: "2023-07-02 11:15",
      score: 90,
      classId: "C2",
      className: "Class B",
    },
    {
      studentName: "Chris Martin",
      studentId: "S20005",
      quizName: "PT2",
      state: "done",
      submissionTime: "2023-07-02 11:20",
      score: 88,
      classId: "C2",
      className: "Class B",
    },
    {
      studentName: "Amy Clark",
      studentId: "S20006",
      quizName: "PT2",
      state: "done",
      submissionTime: "2023-07-02 11:25",
      score: 85,
      classId: "C2",
      className: "Class B",
    },
    {
      studentName: "Brian Lewis",
      studentId: "S20007",
      quizName: "PT2",
      state: "done",
      submissionTime: "2023-07-02 11:30",
      score: 91,
      classId: "C2",
      className: "Class B",
    },
    {
      studentName: "Diana Walker",
      studentId: "S20008",
      quizName: "PT2",
      state: "done",
      submissionTime: "2023-07-02 11:35",
      score: 93,
      classId: "C2",
      className: "Class B",
    },
    {
      studentName: "Jack Hall",
      studentId: "S20009",
      quizName: "PT2",
      state: "done",
      submissionTime: "2023-07-02 11:40",
      score: 86,
      classId: "C2",
      className: "Class B",
    },
    {
      studentName: "Lily Allen",
      studentId: "S20010",
      quizName: "PT2",
      state: "done",
      submissionTime: "2023-07-02 11:45",
      score: 94,
      classId: "C2",
      className: "Class B",
    },
    // Class C, PT1
    {
      studentName: "Ethan King",
      studentId: "S30001",
      quizName: "PT1",
      state: "done",
      submissionTime: "2023-07-01 12:00",
      score: 86,
      classId: "C3",
      className: "Class C",
    },
    {
      studentName: "Sophia Wright",
      studentId: "S30002",
      quizName: "PT1",
      state: "done",
      submissionTime: "2023-07-01 12:05",
      score: 89,
      classId: "C3",
      className: "Class C",
    },
    {
      studentName: "Mason Scott",
      studentId: "S30003",
      quizName: "PT1",
      state: "done",
      submissionTime: "2023-07-01 12:10",
      score: 90,
      classId: "C3",
      className: "Class C",
    },
    {
      studentName: "Olivia Green",
      studentId: "S30004",
      quizName: "PT1",
      state: "done",
      submissionTime: "2023-07-01 12:15",
      score: 85,
      classId: "C3",
      className: "Class C",
    },
    {
      studentName: "Liam Adams",
      studentId: "S30005",
      quizName: "PT1",
      state: "done",
      submissionTime: "2023-07-01 12:20",
      score: 91,
      classId: "C3",
      className: "Class C",
    },
    {
      studentName: "Emma Baker",
      studentId: "S30006",
      quizName: "PT1",
      state: "done",
      submissionTime: "2023-07-01 12:25",
      score: 88,
      classId: "C3",
      className: "Class C",
    },
    {
      studentName: "Aiden Clark",
      studentId: "S30007",
      quizName: "PT1",
      state: "done",
      submissionTime: "2023-07-01 12:30",
      score: 87,
      classId: "C3",
      className: "Class C",
    },
    {
      studentName: "Isabella Gonzalez",
      studentId: "S30008",
      quizName: "PT1",
      state: "done",
      submissionTime: "2023-07-01 12:35",
      score: 89,
      classId: "C3",
      className: "Class C",
    },
    {
      studentName: "Daniel Rodriguez",
      studentId: "S30009",
      quizName: "PT1",
      state: "done",
      submissionTime: "2023-07-01 12:40",
      score: 90,
      classId: "C3",
      className: "Class C",
    },
    {
      studentName: "Mia Lee",
      studentId: "S30010",
      quizName: "PT1",
      state: "done",
      submissionTime: "2023-07-01 12:45",
      score: 92,
      classId: "C3",
      className: "Class C",
    },
    // Class C, PT2
    {
      studentName: "Ethan King",
      studentId: "S30001",
      quizName: "PT2",
      state: "done",
      submissionTime: "2023-07-02 12:00",
      score: 88,
      classId: "C3",
      className: "Class C",
    },
    {
      studentName: "Sophia Wright",
      studentId: "S30002",
      quizName: "PT2",
      state: "done",
      submissionTime: "2023-07-02 12:05",
      score: 87,
      classId: "C3",
      className: "Class C",
    },
    {
      studentName: "Mason Scott",
      studentId: "S30003",
      quizName: "PT2",
      state: "done",
      submissionTime: "2023-07-02 12:10",
      score: 91,
      classId: "C3",
      className: "Class C",
    },
    {
      studentName: "Olivia Green",
      studentId: "S30004",
      quizName: "PT2",
      state: "done",
      submissionTime: "2023-07-02 12:15",
      score: 86,
      classId: "C3",
      className: "Class C",
    },
    {
      studentName: "Liam Adams",
      studentId: "S30005",
      quizName: "PT2",
      state: "done",
      submissionTime: "2023-07-02 12:20",
    },
  ];

  return (
    <div className="table_managementGrade">
      <MenuComponent role="teacher" />
      <Box
        sx={{
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          marginTop: "2rem",
          width: "700px",
        }}
      >
        <h1 style={{ marginBottom: "1.5rem" }}>Student Grade Overview</h1>
        <ManagementGrade data={fakeData} />
      </Box>
    </div>
  );
};

export default TeacherGrade;